<?php

/**
 * @file
 * Provides extra menu links for the core drupal toolbar.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_toolbar().
 */
function admin_toolbar_tools_toolbar() {
  $items = [];
  $items['admin_toolbar_tools'] = [
    '#type' => 'toolbar_item',
    'tab' => [
      '#type' => 'link',
      '#attributes' => [
        'class' => ['toolbar-icon', 'toolbar-icon-admin-toolbar-tools-help'],
      ],
    ],
    '#attached' => [
      'library' => [
        'admin_toolbar_tools/toolbar.icon',
      ],
    ],
  ];
  return $items;
}

/**
 * Implements hook_help().
 */
function admin_toolbar_tools_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.admin_toolbar_tools':
      $output = '';
      $output .= '<p>' . t('The Admin Toolbar Extra Tools module comes packaged with the <a href="https://www.drupal.org/project/admin_toolbar"> Admin Toolbar</a> module and adds functionality to it. The additional functionality is accessed thru extra links on the main administration <a href="https://www.drupal.org/project/toolbar">Toolbar</a>.  Some links to Admin Toolbar Extra Tools administration pages are located at the bottom of this page. For more information, see the <a href="https://www.drupal.org/node/2713693">online documentation for Admin Toolbar</a>') . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<p>' . t('To use Admin Toolbar Extra Tools just install it like any other module.  There is no other configuration required. The Admin Toolbar functionality can be further extended by installing complimentary modules.  See <a href="https://www.drupal.org/project/admin_toolbar">Admin Toolbar</a> for a complete listing of these complimentary modules.') . '</p>';

      return $output;
  }
}

/**
 * Implements hook_menu_links_discovered_alter().
 */
function admin_toolbar_tools_menu_links_discovered_alter(&$links) {
  $links['admin_toolbar_tools.help'] = [
    'title' => 'Tools',
    'route_name' => '<front>',
    'parent' => 'system.admin',
    'weight' => -100,
  ];
  // Add system links.
  $links['system.admin_index'] = [
    'title' => 'Index',
    'route_name' => 'system.admin_index',
    'parent' => 'admin_toolbar_tools.help',
    'weight' => -100,
  ];
  $links['system.run_cron'] = [
    'title' => 'Run cron',
    'route_name' => 'admin_toolbar.run.cron',
    'parent' => 'admin_toolbar_tools.help',
    'weight' => -8,
  ];
  $links['system.db_update'] = [
    'title' => 'Run Updates',
    'route_name' => 'system.db_update',
    'parent' => 'admin_toolbar_tools.help',
    'weight' => -6,
  ];
  $links['system.modules_uninstall'] = [
    'title' => 'Uninstall',
    'route_name' => 'system.modules_uninstall',
    'parent' => 'system.modules_list',
  ];
  // Defining the machine names for all core content entities.
  $content_entities = [
    "block_content" => [
      "content_entity" => "block_content",
      "config_entity" => "block_content_type",
    ],
    "comment" => [
      "content_entity" => "comment",
      "config_entity" => "comment_type",
    ],
    "contact" => [
      "content_entity" => "contact_message",
      "config_entity" => "contact_form",
    ],
    "node" => [
      "content_entity" => "node",
      "config_entity" => "node_type",
    ],
    "taxonomy" => [
      "content_entity" => "taxonomy_term",
      "config_entity" => "taxonomy_vocabulary",
    ],
  ];

  // Add common links to entities if parent module exists.
  // The common links for entities are:
  // - Editing an entity, Deleting an entity, managing fields for an entity,
  // - manage form display for an entity, entity view display.
  // - Others links relating to entity are included here as well.
  foreach ($content_entities as $module_name => $entities) {
    if (\Drupal::moduleHandler()->moduleExists($module_name)) {
      $config_entity = $entities['config_entity'];
      $content_entity = $entities['content_entity'];
      foreach (\Drupal::entityManager()
                 ->getBundleInfo($content_entity) as $machine_name => $bundle) {
        $links["entity." . $config_entity . ".edit_form." . $machine_name] = [
          'title' => $bundle['label'],
          'route_name' => "entity." . $config_entity . ".edit_form",
          'parent' => "entity." . $config_entity . ".collection",
          'route_parameters' => [$config_entity => $machine_name],
        ];
        $links["entity." . $config_entity . ".delete_form." . $machine_name] = [
          'title' => 'Delete',
          'route_name' => "entity." . $config_entity . ".delete_form",
          'parent' => "entity." . $config_entity . ".edit_form." . $machine_name,
          'route_parameters' => [$config_entity => $machine_name],
        ];
        if (\Drupal::moduleHandler()->moduleExists('field_ui')) {
          $links["entity." . $content_entity . ".field_ui_fields" . $machine_name] = [
            'title' => 'Manage fields',
            'route_name' => "entity." . $content_entity . ".field_ui_fields",
            'parent' => "entity." . $config_entity . ".edit_form." . $machine_name,
            'route_parameters' => [$config_entity => $machine_name],
          ];
          $links["entity.entity_form_display." . $content_entity . ".default" . $machine_name] = [
            'title' => 'Manage form display',
            'route_name' => "entity.entity_form_display." . $content_entity . ".default",
            'parent' => "entity." . $config_entity . ".edit_form." . $machine_name,
            'route_parameters' => [$config_entity => $machine_name
            ],
          ];
          $links["entity.entity_view_display." . $content_entity . ".default" . $machine_name] = [
            'title' => 'Manage display',
            'route_name' => "entity.entity_view_display." . $content_entity . ".default",
            'parent' => "entity." . $config_entity . ".edit_form." . $machine_name,
            'route_parameters' => [$config_entity => $machine_name],
          ];
        }
        if (\Drupal::moduleHandler()->moduleExists('devel')) {
          $links["entity.$config_entity.devel_load." . $machine_name] = [
            'title' => 'Devel',
            'route_name' => "entity." . $config_entity . ".devel_load",
            'parent' => "entity." . $config_entity . ".edit_form." . $machine_name,
            'route_parameters' => [$config_entity => $machine_name],
          ];
        }
      }
      if ($moduleHandler->moduleExists('devel') && in_array('entity.' . $content_entity_bundle . '.devel_load', $routes)) {
        $links['entity.' . $content_entity_bundle . '.devel_load.' . $machine_name] = array(
          'title' => t('Devel'),
          'route_name' => 'entity.' . $content_entity_bundle . '.devel_load',
          'menu_name' => 'admin',
          'parent' => $content_entity_bundle_root,
          'route_parameters' => array($content_entity_bundle => $machine_name),
          'weight' => 4,
        );
      }
      if (in_array('entity.' . $content_entity_bundle . '.delete_form', $routes)) {
        $links['entity.' . $content_entity_bundle . '.delete_form.' . $machine_name] = array(
          'title' => t('Delete'),
          'route_name' => 'entity.' . $content_entity_bundle . '.delete_form',
          'menu_name' => 'admin',
          'parent' => $content_entity_bundle_root,
          'route_parameters' => array($content_entity_bundle => $machine_name),
          'weight' => 5,
        );
      }
    }
  }

// Add user links.
  $links['user.admin_create'] = [
    'title' => 'Add user',
    'route_name' => 'user.admin_create',
    'menu_name' => 'admin',
    'parent' => 'entity.user.collection',
  ];
  $links['user.admin_permissions'] = [
    'title' => 'Permissions',
    'route_name' => 'user.admin_permissions',
    'menu_name' => 'admin',
    'parent' => 'entity.user.collection',
  ];
  $links['entity.user_role.collection'] = [
    'title' => 'Roles',
    'route_name' => 'entity.user_role.collection',
    'menu_name' => 'admin',
    'parent' => 'entity.user.collection',
  ];
  $links['user.logoutt'] = [
    'title' => 'Logout',
    'route_name' => 'user.logout',
    'parent' => 'admin_toolbar_tools.help',
    'weight' => 10,
  ];
  $links['user.role_add'] = [
    'title' => 'Add role',
    'route_name' => 'user.role_add',
    'menu_name' => 'admin',
    'parent' => 'entity.user_role.collection',
    'weight' => -5,
  ];
  if (\Drupal::moduleHandler()->moduleExists('field_ui')) {
    $links['entity.user.field_ui_fields_'] = [
      'title' => 'Manage fields',
      'route_name' => 'entity.user.field_ui_fields',
      'menu_name' => 'admin',
      'parent' => 'entity.user.admin_form',
    ];
    $links['entity.entity_form_display.user.default_'] = [
      'title' => 'Manage form display',
      'route_name' => 'entity.entity_form_display.user.default',
      'menu_name' => 'admin',
      'parent' => 'entity.user.admin_form',
    ];
    $links['entity.entity_view_display.user.default_'] = [
      'title' => 'Manage display',
      'route_name' => 'entity.entity_view_display.user.default',
      'menu_name' => 'admin',
      'parent' => 'entity.user.admin_form',
    ];
  }
  foreach (user_roles() as $role) {
    $links['entity.user_role.edit_form.' . $role->id()] = [
      'title' => $role->label(),
      'route_name' => 'entity.user_role.edit_form',
      'menu_name' => 'admin',
      'parent' => 'entity.user_role.collection',
      'route_parameters' => ['user_role' => $role->id()],
    ];
    $links['entity.user_role.edit_permissions_form.' . $role->id()] = [
      'title' => "Edit permissions",
      'route_name' => 'entity.user_role.edit_permissions_form',
      'menu_name' => 'admin',
      'parent' => 'entity.user_role.edit_form.' . $role->id(),
      'route_parameters' => ['user_role' => $role->id()],
    ];
    $links['entity.user_role.delete_form.' . $role->id()] = [
      'title' => "Delete",
      'route_name' => 'entity.user_role.delete_form',
      'menu_name' => 'admin',
      'parent' => 'entity.user_role.edit_form.' . $role->id(),
      'route_parameters' => ['user_role' => $role->id()],
    ];
    if (\Drupal::moduleHandler()->moduleExists('devel')) {
      $links['entity.user_role.devel_load.' . $role->id()] = [
        'title' => "Devel",
        'route_name' => 'entity.user_role.devel_load',
        'menu_name' => 'admin',
        'parent' => 'entity.user_role.edit_form.' . $role->id(),
        'route_parameters' => ['user_role' => $role->id()],
      ];
    }
  }

  if ($moduleHandler->moduleExists('node')) {
    $links['node.add_page']['parent'] = 'system.admin_content';
    $links['node.type_add'] = [
      'title' => 'Add content type',
      'route_name' => 'node.type_add',
      'menu_name' => 'admin',
      'parent' => 'entity.node_type.collection',
      'weight' => -5,
    ];
    // Add node links for each content type.
    foreach (node_type_get_names() as $machine_name => $label) {
      $links['node.add.' . $machine_name] = [
        'title' => $label,
        'route_name' => 'node.add',
        'parent' => 'node.add_page',
        'route_parameters' => ['node_type' => $machine_name],
      ];
    }
  }
  if (\Drupal::moduleHandler()->moduleExists('field_ui')) {
    $links['field_ui.entity_form_mode_add'] = [
      'title' => 'Add new form mode',
      'route_name' => 'field_ui.entity_form_mode_add',
      'menu_name' => 'admin',
      'parent' => 'entity.entity_form_mode.collection',
    ];
    $links['field_ui.entity_view_mode_add'] = [
      'title' => 'Add new view mode',
      'route_name' => 'field_ui.entity_view_mode_add',
      'menu_name' => 'admin',
      'parent' => 'entity.entity_view_mode.collection',
    ];
  }
  if (\Drupal::moduleHandler()->moduleExists('taxonomy')) {
    $links['entity.taxonomy_vocabulary.add_form'] = [
      'title' => 'Add vocabulary',
      'route_name' => 'entity.taxonomy_vocabulary.add_form',
      'menu_name' => 'admin',
      'parent' => 'entity.taxonomy_vocabulary.collection',
      'weight' => -5,
    ];
    foreach (\Drupal::entityManager()->getBundleInfo('taxonomy_term') as $machine_name => $bundle) {
      $links['entity.taxonomy_term.add_form.' . $machine_name] = [
        'title' => $bundle['label'],
        'route_name' => 'entity.taxonomy_term.add_form',
        'parent' => 'entity.taxonomy_vocabulary.edit_form',
        'route_parameters' => ['taxonomy_vocabulary' => $machine_name],
      ];
    }
  }
  if (\Drupal::moduleHandler()->moduleExists('menu_ui')) {
    $links['entity.menu.add_form'] = [
      'title' => 'Add menu',
      'route_name' => 'entity.menu.add_form',
      'menu_name' => 'admin',
      'parent' => 'entity.menu.collection',
      'weight' => -50,
    ];
    // Adding links to /admin/structure/menu.
    foreach (menu_ui_get_menus() as $machine_name => $label) {
      $links['entity.menu.edit_form.' . $machine_name] = [
        'title' => $label,
        'route_name' => 'entity.menu.edit_form',
        'menu_name' => 'admin',
        'parent' => 'entity.menu.collection',
        'route_parameters' => ['menu' => $machine_name],
      ];
      $links['entity.menu.delete_form.' . $machine_name] = [
        'title' => 'Delete',
        'route_name' => 'entity.menu.delete_form',
        'menu_name' => 'admin',
        'parent' => 'entity.menu.edit_form.' . $machine_name,
        'route_parameters' => ['menu' => $machine_name],
      ];
      if (\Drupal::moduleHandler()->moduleExists('devel')) {
        $links['entity.menu.devel_load.' . $machine_name] = [
          'title' => 'Devel',
          'route_name' => 'entity.menu.devel_load',
          'menu_name' => 'admin',
          'parent' => 'entity.menu.edit_form.' . $machine_name,
          'route_parameters' => ['menu' => $machine_name],
        ];
      }
      $links['entity.menu.add_link_form.' . $machine_name] = [
        'title' => 'Add link',
        'route_name' => 'entity.menu.add_link_form',
        'menu_name' => 'admin',
        'parent' => 'entity.menu.edit_form.' . $machine_name,
        'route_parameters' => ['menu' => $machine_name],
      ];
    }
  }

  // If module block_content is enabled.
  if (\Drupal::moduleHandler()->moduleExists('block_content')) {
    $links['block_content.add_page'] = [
      'title' => 'Add custom block',
      'route_name' => 'block_content.add_page',
      'menu_name' => 'admin',
      'parent' => 'block.admin_display',
      'weight' => -100,
    ];
    $links['entity.block_content.collection'] = [
      'title' => 'Custom block library',
      'route_name' => 'entity.block_content.collection',
      'menu_name' => 'admin',
      'parent' => 'block.admin_display',
    ];
    $links['entity.block_content_type.collection'] = [
      'title' => 'Types',
      'route_name' => 'entity.block_content_type.collection',
      'menu_name' => 'admin',
      'parent' => 'block.admin_display',
    ];
  }
  // If module contact is enabled.
  if (\Drupal::moduleHandler()->moduleExists('contact')) {
    $links['contact.form_add'] = [
      'title' => 'Add contact form',
      'route_name' => 'contact.form_add',
      'menu_name' => 'admin',
      'parent' => 'entity.contact_form.collection',
      'weight' => -5,
    ];
  }
  // If module update is enabled.
  if (\Drupal::moduleHandler()->moduleExists('update')) {
    $links['update.module_update'] = [
      'title' => 'Update',
      'route_name' => 'update.module_update',
      'menu_name' => 'admin',
      'parent' => 'system.modules_list',
    ];
    $links['update.module_install'] = [
      'title' => 'Install new module',
      'route_name' => 'update.module_install',
      'menu_name' => 'admin',
      'parent' => 'system.modules_list',
    ];
  }
  if (\Drupal::moduleHandler()->moduleExists('devel')) {
    $links['admin_development'] = [
      'title' => 'Development',
      'route_name' => 'system.admin_config_development',
      'menu_name' => 'admin',
      'parent' => 'admin_toolbar_tools.help',
      'weight' => -8,
    ];
    $links['devel.admin_settings'] = [
      'title' => 'Devel settings',
      'route_name' => 'devel.admin_settings',
      'parent' => 'admin_development',
    ];
    $links['devel.configs_list'] = [
      'title' => 'Config editor',
      'route_name' => 'devel.configs_list',
      'parent' => 'admin_development',
    ];
    $links['devel.reinstall'] = [
      'title' => 'Reinstall Modules',
      'route_name' => 'devel.reinstall',
      'parent' => 'admin_development',
    ];
    $links['devel.menu_rebuild'] = [
      'title' => 'Rebuild Menu',
      'route_name' => 'devel.menu_rebuild',
      'parent' => 'admin_development',
    ];
    $links['devel.state_system_page'] = [
      'title' => 'State editor',
      'route_name' => 'devel.state_system_page',
      'parent' => 'admin_development',
    ];
    $links['devel.theme_registry'] = [
      'title' => 'Theme registry',
      'route_name' => 'devel.theme_registry',
      'parent' => 'admin_development',
    ];
    $links['devel.entity_info_page'] = [
      'title' => 'Entity Info',
      'route_name' => 'devel.entity_info_page',
      'parent' => 'admin_development',
    ];
    $links['devel.execute_php'] = [
      'title' => 'Execute PHP',
      'route_name' => 'devel.execute_php',
      'parent' => 'admin_development',
    ];
    $links['devel.session'] = [
      'title' => 'View Session',
      'route_name' => 'devel.session',
      'parent' => 'admin_development',
    ];
    $links['devel.elements_page'] = [
      'title' => 'Hook_elements',
      'route_name' => 'devel.elements_page',
      'parent' => 'admin_development',
    ];
  }
  // If module views_ui enabled.
  if (\Drupal::moduleHandler()->moduleExists('views_ui')) {
    $links['views_ui.add'] = [
      'title' => t('Add new view'),
      'route_name' => 'views_ui.add',
      'menu_name' => 'admin',
      'parent' => 'entity.view.collection',
      'weight' => -5,
    ];
  }
  $links['system.theme_settings_'] = [
    'title' => t('Settings'),
    'route_name' => 'system.theme_settings',
    'menu_name' => 'admin',
    'parent' => 'system.themes_page',
  ];
  if (\Drupal::moduleHandler()->moduleExists('update')) {
    $links['update.theme_install_'] = [
      'title' => t('Install new theme'),
      'route_name' => 'update.theme_install',
      'menu_name' => 'admin',
      'parent' => 'system.themes_page',
    ];
    $links['update.theme_update_'] = [
      'title' => t('Update'),
      'route_name' => 'update.theme_update',
      'menu_name' => 'admin',
      'parent' => 'system.themes_page',
    ];
    //List of installed themes.
    $installed_themes = installedThemes();
    foreach ($installed_themes as $key_theme => $label_theme) {
      $links['system.theme_settings_theme' . '.' . $key_theme] = [
        'title' => t($label_theme),
        'route_name' => 'system.theme_settings_theme',
        'menu_name' => 'admin',
        'parent' => 'system.theme_settings_',
        'route_parameters' => [
          'theme' => $key_theme,
        ],
      ];
    }
  }
}

/**
 * Return installed themes.
 *
 * @return array
 *   An array of friendly theme names, keyed by the machine name.
 */
function admin_toolbar_tools_installed_themes() {
  $all_themes = \Drupal::service('theme_handler')->listInfo();
  $themes_installed = [];
  foreach ($all_themes as $key_theme => $theme) {
    if (\Drupal::service('theme_handler')->hasUi($key_theme)) {
      $themes_installed[$key_theme] = $theme->getName();
    }
  }

  return $themes_installed;
}

/**
 * Get all links related to entity.
 *
 * @param string $entity_type_id
 *   The machine name for the entity type.
 *
 * @return array
 *   The links for the entity type.
 */
function admin_toolbar_tools_get_links($entity_type_id) {
  $entity = \Drupal::entityTypeManager()->getDefinition($entity_type_id);
  // Get all links related to entity.
  $links = $entity->getLinkTemplates();

  return $links;
}
